version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  lint-and-build:
    docker:
      - image: cimg/node:16.7.0
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint
      - run: npm run build
workflows:
  lint-and-build-portfolio:
    jobs:
      - lint-and-build
